### ISSUE TITLE
Configuration on construct

### ISSUE THREAD

**Issue by juliardi** [nsulistiyawan/bpjs#1]
How about moving the configuration from `BpjsService::configure` to `BpjsService::_construct` ?
That way, the initiated object would be ready to use right from the start

**Comment by nsulistiyawan** [comment]
sure, i think that's will make the code cleaner, do u wanna send pull request for it?  @juliardi

**Comment by juliardi** [comment]
I've created a pull request, please review it

**Comment by nsulistiyawan** [comment]
looks good, thanks! @juliardi
