### ISSUE TITLE
[Bertanya]

### ISSUE THREAD

**Issue by MuhammadFakhrurrozi** [nsulistiyawan/bpjs#5]
Kenapa writer tidak mencantumkan dokumentasi untuk pemanfaatan REST v-claim untuk service monitoring, seperti dokumentasi service peserta ?
Terima kasih

**Comment by nsulistiyawan** [comment]
hi, sorry baru kebaca, dan udah lama ga pegang project simrs lagi nih
ada endpoint yang paling update untuk sekarang? biar saya update lagi dokumentasi dan kodenya :)
